# Generated by Django 6.0.2 on 2026-02-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(default='COMPUTER SCIENCE', max_length=100),
            preserve_default=False,
        ),
    ]
