# Generated by Django 6.0.2 on 2026-02-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_course_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics and Communication', 'Electronics and Communication'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Business Administration', 'Business Administration')], max_length=100),
        ),
    ]
